// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyDe_p6UZx3En2tMVVlJe_S7zniCUVj_7cY',
    appId: '1:1014416177125:web:4765f4d1517952696b610c',
    messagingSenderId: '1014416177125',
    projectId: 'mymovies-app-project',
    authDomain: 'mymovies-app-project.firebaseapp.com',
    storageBucket: 'mymovies-app-project.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:1014416177125:android:25e76a5f2f3087aa60610c',
    messagingSenderId: '1014416177125',
    projectId: 'mymovies-app-project',
    storageBucket: 'mymovies-app-project.firebasestorage.app',
  );
}
