name: Dependency Vulnerability Scan

on:
  push:
    branches: [ main, master ]
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'
  schedule:
    - cron: '0 0 * * 1' # Cek setiap Senin jam 12 malam

concurrency:
  group: audit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vulnerability-scan:
    name: OSV-Scanner (Google)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --recursive
            ./
